import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'page1_model.dart';
export 'page1_model.dart';

class Page1Widget extends StatefulWidget {
  const Page1Widget({super.key});

  @override
  State<Page1Widget> createState() => _Page1WidgetState();
}

class _Page1WidgetState extends State<Page1Widget> {
  late Page1Model _model;

  final scaffoldKey = GlobalKey<ScaffoldState>();

  @override
  void initState() {
    super.initState();
    _model = createModel(context, () => Page1Model());

    logFirebaseEvent('screen_view', parameters: {'screen_name': 'page1'});
    WidgetsBinding.instance.addPostFrameCallback((_) => setState(() {}));
  }

  @override
  void dispose() {
    _model.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _model.unfocusNode.canRequestFocus
          ? FocusScope.of(context).requestFocus(_model.unfocusNode)
          : FocusScope.of(context).unfocus(),
      child: Scaffold(
        key: scaffoldKey,
        appBar: AppBar(
          backgroundColor: FlutterFlowTheme.of(context).primary,
          automaticallyImplyLeading: false,
          title: Text(
            'Page Title',
            style: FlutterFlowTheme.of(context).headlineMedium.override(
                  fontFamily: 'Barlow Condensed',
                  color: Colors.white,
                  fontSize: 22.0,
                  letterSpacing: 0.0,
                ),
          ),
          actions: const [],
          centerTitle: false,
          elevation: 2.0,
        ),
        body: SafeArea(
          top: true,
          child: Column(
            mainAxisSize: MainAxisSize.max,
            children: [
              Expanded(
                child: MarkdownBody(
                  data:
                      '''# Disclaimer: Important Information Regarding AstroGenius

AstroGenius is an AI-powered platform designed to provide astrological guidance based on the principles of astrology. While we strive to offer accurate and insightful interpretations, it is essential to understand the following:

## For Entertainment Purposes Only

The information and guidance provided by AstroGenius should be considered for entertainment purposes only.

## Subject to Interpretation

Astrology is a complex field, and interpretations may vary. The guidance generated by AstroGenius is based on AI algorithms trained on astrological principles, but different interpretations are possible. Use the provided insights as a starting point for personal reflection and decision-making.

## Not a Guarantee of Future Events

Astrological predictions are not absolute certainties. They are based on the understanding of celestial influences and patterns. Life is subject to numerous factors and individual choices that can shape outcomes differently from what astrology suggests.

## User Responsibility

Users of AstroGenius are responsible for their own actions and decisions. We encourage you to exercise discretion, critical thinking, and personal judgment when considering the guidance provided by the platform.

## Accuracy and Technical Limitations

While we strive for accuracy, AstroGenius may have inherent limitations or technical constraints. Factors such as incorrect birth information, algorithmic variations, or data inconsistencies can impact the accuracy of predictions. Please use the platform with this understanding.

By using AstroGenius, you acknowledge and agree to these disclaimers. We recommend combining astrological insights with your own intuition and seeking professional advice when necessary.

Please proceed with AstroGenius with full awareness of its limitations and for entertainment purposes only.''',
                  selectable: true,
                  onTapLink: (_, url, __) => launchURL(url!),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
